services:
  backend-localstack:
    container_name: backend-localstack
    hostname: backend-localstack
    image: localstack/localstack:0.14.0
    environment:
      - SERVICES=sns,sqs,s3
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
    ports:
      - 4566:4566

  postgres:
    image: postgres:13
    container_name: starter-template-postgres
    hostname: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"  # Expose Postgres on port 5432
    networks:
      - app_network

  redis:
    image: 'redis:alpine'
    container_name: starter-template-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
